---
- hosts: all
  become: yes

  tasks:
    - name: Update cache and install Nginx
      dnf:
        name: nginx
        state: latest
        update_cache: yes

    - name: Install Certbot for Nginx
      dnf:
        name: certbot-nginx
        state: latest

    - name: Ensure Nginx is enabled and running
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Download website files from URL
      get_url:
        url: https://raw.githubusercontent.com/R-D-Y/Ansible-tf-Webserver/main/HTML-PAGE-NODE-1.html
        dest: /usr/share/nginx/html/index.html
        mode: '0644'

    - name: Obtain SSL certificate
      shell: certbot --nginx -d yourdomain.com --non-interactive --agree-tos --email your-email@example.com

    - name: Ensure nginx is restarted
      systemd:
        name: nginx
        state: restarted
