- hosts: all
  become: yes
  vars:
    ssl_cert: "/etc/ssl/certs/nginx-selfsigned.crt"
    ssl_key: "/etc/ssl/private/nginx-selfsigned.key"

  tasks:
    - name: Update cache and install Nginx
      dnf:
        name: nginx
        state: latest
        update_cache: yes

    - name: Create SSL directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /etc/ssl/certs
        - /etc/ssl/private

    - name: Generate OpenSSL private key
      openssl_privatekey:
        path: "{{ ssl_key }}"

    - name: Generate OpenSSL certificate
      openssl_certificate:
        path: "{{ ssl_cert }}"
        privatekey_path: "{{ ssl_key }}"
        provider: selfsigned

    - name: Download website files from URL
      get_url:
        url: https://raw.githubusercontent.com/R-D-Y/Ansible-tf-Webserver/main/HTML-PAGE-NODE-1.html
        dest: /usr/share/nginx/html/index.html
        mode: '0644'

    - name: Configure Nginx to use SSL
      blockinfile:
        path: /etc/nginx/nginx.conf
        block: |
          server {
            listen 443 ssl;
            server_name _; # Use your domain or keep underscore for default
            ssl_certificate {{ ssl_cert }};
            ssl_certificate_key {{ ssl_key }};

            location / {
              root /usr/share/nginx/html;
              index index.html index.htm;
            }
          }

    - name: Ensure Nginx is enabled and running
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Ensure nginx is restarted
      systemd:
        name: nginx
        state: restarted
