---
- hosts: Node2
  become: yes
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www
    app_root: html_demo_site-main
  tasks:
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Download website files from URL
      get_url:
        url: https://raw.githubusercontent.com/R-D-Y/HTML-PROJET/main/HTML-PAGE-NODE-2.html
        dest: /tmp/index.html

    - name: Copy website files to the server's document root
      copy:
        src: /tmp/index.html
        dest: /var/www/html
        mode: preserve
        remote_src: yes

    - name: Create sites-available directory
      file:
        path: /etc/nginx/sites-available
        state: directory
        mode: 0755

    - name: Create sites-enabled directory
      file:
        path: /etc/nginx/sites-enabled
        state: directory
        mode: 0755

    - name: Apply Nginx template
      template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
        force: yes
      notify: Restart Nginx

        #- name: Allow all access to tcp port 80
      #ufw:
        #rule: allow
          #port: '80'
          #proto: tcp

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted