- name: Setup MySQL and Database
  hosts: all
  become: yes
  vars:
    mysql_root_password: "rootpassword"
    mysql_database: "my_app"
    mysql_user: "my_user"
    mysql_password: "userpassword"
    python_script_path: "./script.py"
  tasks:
    - name: Install MariaDB (compatible avec MySQL)
      dnf:
        name: mariadb105-server
        state: present

    - name: Start MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Secure MariaDB installation
      command: >
        mysql_secure_installation --use-default --password={{ mysql_root_password }}
      args:
        creates: /var/lib/mysql/.mysql_secure_installation

    - name: Create administrative user for MariaDB
      mysql_user:
        name: admin
        password: "{{ mysql_root_password }}"
        host: localhost
        priv: '*.*:ALL,GRANT'
        state: present

    - name: Set MariaDB root password (using admin user)
      mysql_user:
        login_user: admin
        login_password: "{{ mysql_root_password }}"
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        state: present

    - name: Install required Python packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

    - name: Install MySQL connector for Python
      pip:
        name: mysql-connector-python

    - name: Copy the Python script to the server
      copy:
        src: "{{ python_script_path }}"
        dest: /tmp/script.py
        mode: '0755'

    - name: Execute the Python script to setup the database
      command: python3 /tmp/script.py
