- name: Setup MySQL and Database
  hosts: db_servers
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set MySQL root password
      mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        state: present

    - name: Install required Python packages
      apt:
        name: "{{ item }}"
      loop:
        - python3
        - python3-pip

    - name: Install MySQL connector for Python
      pip:
        name: mysql-connector-python

    - name: Copy the Python script to the server
      copy:
        src: "{{ python_script_path }}"
        dest: /tmp/script.py
        mode: '0755'

    - name: Execute the Python script to setup the database
      command: python3 /tmp/script.py
