- name: Setup MySQL and Database
  hosts: all
  become: yes
  vars:
    mysql_root_password: "rootpassword"
    mysql_database: "my_app"
    mysql_user: "my_user"
    mysql_password: "userpassword"
    python_script_path: "/path/to/your/script.py"
  tasks:
    - name: Install MySQL
      dnf:
        name: mariadb-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set MySQL root password
      mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        state: present

    - name: Install required Python packages
      dnf:
        name: "{{ item }}"
      loop:
        - python3
        - python3-pip

    - name: Install MySQL connector for Python
      pip:
        name: mysql-connector-python

    - name: Copy the Python script to the server
      copy:
        src: "{{ python_script_path }}"
        dest: /tmp/script.py
        mode: '0755'

    - name: Execute the Python script to setup the database
      command: python3 /tmp/script.py
